#language: php
#php:
  #- 5.6
  #- 5.5
  #- 5.4
  #- 5.3


#language: ruby
#rvm:
    #- 2.0.0
    #- 1.9.3
    #- 1.9.2
    #- 1.8.7

language: node_js
node_js:
    - 0.11
    - 0.10
    - 0.9
    #- 0.8
    #- 0.6

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 5
    - node_modules/.bin/buster-server &
    - sleep 5
    - firefox http://localhost:1111/capture &
    - sleep 5

script:
    - "npm test"
